spring:
  profiles:
    active: local


debug: true

---

spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      database: spring-webflux-demo


---

spring:
  config:
    activate:
      on-profile:
        - non-prod
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
