spring:
  profiles:
    active: local
---

spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: local


---

spring:
  config:
    activate:
      on-profile:
        - non-prod
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
